name: "🔗 New Link"
about: "Suggest a new AGENTS.md resource"
labels: enhancement
body:
  - type: input
    id: url
    attributes:
      label: URL
      placeholder: "https://..."
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Why is this resource awesome?
      placeholder: "Short, objective description (30‑60 chars)."
    validations:
      required: true